### ISSUE TITLE
Transfer bartelink/PlayingWithProjectionsFsharp ?

### ISSUE THREAD

**Issue by bartelink** [PlayingWithProjections/PlayingWithProjections.github.io#1]
I'm happy to have https://github.com/bartelink/PlayingWithProjectionsFsharp transferred to the org if you're interested

(I also have an answer branch but I'll keep that in a fork post-transfer)

**Comment by tcoopman** [comment]
Hi @bartelink,

Thank you very much for this awesome work. I'll try to test it out soon (or @michelgrootjans ) and if that works out we can definitely include it!

**Comment by michelgrootjans** [comment]
Thank you for your submission.

I'm not that fluent in F#, so I cannot judge it idiomatically. It works when you run it, which is the first requirement ;-).

Could you add some instructions for future users that have another dotnetcore version than 2.1. This seems to be a recurring problem for participants.

I'm inviting you to the org so you can add the F# project.

**Comment by bartelink** [comment]
Thanks! Regarding doing things idiomatically, I'll make a fork my side with an answers branch, which might yield a top level driver function analogous to what the C# one had; will do a PR at some point re that.

I believe the opening line covers the dotnetcore versioning story - `netcoreapp` is supported by .NET Core 2.1 or later, and there's really no major advantage to targeting anything later unless e.g. you're going to take advantage of e.g. an ASP.NET feature or Spans, which of course is not relevant to the exercise etc.

The other unfortunate thing thing is that I've pushed my command module off into outer space without a) removing projects, wiki b) renaming to `fsharp` - feel free to do with it as you see fit!

**Comment by tcoopman** [comment]
Thanks, I've renamed the repo to fsharp and added a link from the website as well.

**Comment by bartelink** [comment]
Looks good - I see I have merge access (thanks) but wont use it - can you review/merge if https://github.com/PlayingWithProjections/fsharp/pull/1 ?
